In [1]:
import numpy as np
import pandas as pd

In [3]:
# Retrieve the amount paid > 1500 and payment method via GCash and PayMaya
# Sort the amount paid from highest to lowest
# Calculate the amount paid (total, average, minimum, and maximum)
# Group the total amount paid by payment method
# Write at least three findings in plain language

payments = pd.read_csv('payments.csv')

In [4]:
payments

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid
0,PAY0000001,ORD0000001,GCash,Paid,2024-05-09,2822.72
1,PAY0000002,ORD0000002,COD,Paid,06/25/2024,2499.76
2,PAY0000003,ORD0000003,GCash,Paid,2025-06-10,1983.66
3,PAY0000004,ORD0000004,PayMaya,Failed,2025-06-21,1765.99
4,PAY0000005,ORD0000005,COD,Pending,06/28/2024,1477.53
...,...,...,...,...,...,...
14995,PAY0014996,ORD0014996,GCash,Paid,2025-06-07,1985.86
14996,PAY0014997,ORD0014997,PayMaya,Paid,2025-12-03,1596.22
14997,PAY0014998,ORD0014998,Bank Transfer,Paid,2026-01-05,836.13
14998,PAY0014999,ORD0014999,GCash,Paid,12/19/2025,NaN
14999,PAY0015000,ORD0015000,GCash,Paid,2025-12-14,2227.32

In [5]:
# Retrieve the amount paid > 1500 and payment method via GCash and PayMaya
# Sort the amount paid from highest to lowest

payments_sorted = payments[
    (pd.to_numeric(payments['amount_paid'], errors = 'coerce') > 1500) & 
    ((payments['payment_method'] == 'GCash') | 
    (payments['payment_method'] == 'PayMaya'))
].sort_values('amount_paid', ascending = False)

# Run

payments_sorted

,payment_id,order_id,payment_method,payment_status,payment_date,amount_paid
11392,PAY0011393,ORD0011393,PayMaya,Paid,2025-07-08,5525.51
9819,PAY0009820,ORD0009820,PayMaya,Paid,2024-05-29,4373.93
4955,PAY0004956,ORD0004956,GCash,Paid,2025-02-19,4251.38
5147,PAY0005148,ORD0005148,GCash,Paid,2024-06-30,4182.22
3867,PAY0003868,ORD0003868,GCash,Failed,2025-06-13,3991.49
...,...,...,...,...,...,...
1527,PAY0001528,ORD0001528,PayMaya,Paid,06/29/2025,1500.99
4102,PAY0004103,ORD0004103,GCash,Paid,2024-08-30,1500.97
8782,PAY0008783,ORD0008783,PayMaya,Refunded,2025-08-27,1500.94
4885,PAY0004886,ORD0004886,PayMaya,Paid,2024-02-15,1500.47
5420,PAY0005421,ORD0005421,GCash,Paid,2025-10-04,1500.28

In [6]:
# Calculate the amount paid (total, average, minimum, and maximum)
# Group the total amount paid by payment method

payments_sorted['amount_paid'] = pd.to_numeric(
    payments_sorted['amount_paid'],
    errors = 'coerce'
)

payments_aggregation = (
    payments_sorted.groupby('payment_method')
        .agg(
            amount_paid_sum = ('amount_paid', 'sum'),
            amount_paid_mean = ('amount_paid', 'mean'),
            amount_paid_min = ('amount_paid', 'min'),
            amount_paid_max = ('amount_paid', 'max')
        )
        .reset_index()
)

# Run

payments_aggregation

,payment_method,amount_paid_sum,amount_paid_mean,amount_paid_min,amount_paid_max
0,GCash,2914008.07,2200.912440,1500.28,4251.38
1,PayMaya,2949127.11,2191.030542,1500.47,5525.51

In [7]:
# Write at least three findings in plain language

amount_paid_sum_GCash = payments_aggregation.iloc[0]['amount_paid_sum']
amount_paid_sum_PayMaya = payments_aggregation.iloc[1]['amount_paid_sum']

amount_paid_mean_GCash = payments_aggregation.iloc[0]['amount_paid_mean']
amount_paid_mean_PayMaya = payments_aggregation.iloc[1]['amount_paid_mean']

amount_paid_min_GCash = payments_aggregation.iloc[0]['amount_paid_min']
amount_paid_min_PayMaya = payments_aggregation.iloc[1]['amount_paid_min']

amount_paid_max_GCash = payments_aggregation.iloc[0]['amount_paid_max']
amount_paid_max_PayMaya = payments_aggregation.iloc[1]['amount_paid_max']

In [8]:
print(f"In terms of the amount paid exceeding PHP 1,500.00:", end = "\n")

print(f"â¢ PayMaya registered a sum amounting to PHP {amount_paid_sum_PayMaya:,.2f} ââœ exceeding that of GCash amounting to PHP {amount_paid_sum_GCash:,.2f}.", end = "\n")

print(f"â¢ GCash registered a mean amounting to PHP {amount_paid_mean_GCash:,.2f} ââœ exceeding that of PayMaya amounting to PHP {amount_paid_mean_PayMaya:,.2f}.", end = "\n")

print(f"â¢ PayMaya received payments ranging from PHP {amount_paid_min_PayMaya:,.2f} to {amount_paid_max_PayMaya:,.2f} ââœ varying more than those of GCash ranging from PHP {amount_paid_min_GCash:,.2f} to {amount_paid_max_GCash:,.2f}.")

In terms of the amount paid exceeding PHP 1,500.00:
â¢ PayMaya registered a sum amounting to PHP 2,949,127.11 ââœ exceeding that of GCash amounting to PHP 2,914,008.07.
â¢ GCash registered a mean amounting to PHP 2,200.91 ââœ exceeding that of PayMaya amounting to PHP 2,191.03.
â¢ PayMaya received payments ranging from PHP 1,500.47 to 5,525.51 ââœ varying more than those of GCash ranging from PHP 1,500.28 to 4,251.38.

In [2]:
files = {
    "customers": "customers.csv",
    "products": "products.csv",
    "orders": "orders.csv",
    "order_items": "order_items.csv",
    "payments": "payments.csv",
    "shipments": "shipments.csv",
    "returns": "returns.csv"
}

data = {name: pd.read_csv(path)
        for name, path in files.items()}

for name, df in data.items():
    print(name, df.shape)
    print("======")
    print(df.isna().sum().sort_values(
        ascending=False).head())
    print("duplicates:", df.duplicated().sum())
    print(df.dtypes)
    print()

customers (5050, 13)
======
gender          301
loyalty_tier    266
age             150
phone           147
email           107
dtype: int64
duplicates: 50
customer_id         str
first_name          str
last_name           str
gender              str
age             float64
email               str
phone           float64
region_code         str
region_name         str
city                str
barangay            str
signup_date         str
loyalty_tier        str
dtype: object

products (800, 9)
======
stock_qty       19
product_id       0
product_name     0
category         0
brand            0
dtype: int64
duplicates: 0
product_id          str
product_name        str
brand               str
category            str
unit_cost       float64
unit_price          str
stock_qty       float64
uom                 str
launch_date         str
dtype: object

orders (15075, 8)
======
discount_pct    758
shipping_fee    474
order_id          0
customer_id       0
order_status      0
dtype: int64
duplicates: 75
order_id               str
customer_id            str
order_datetime         str
order_status           str
sales_channel          str
shipping_method        str
discount_pct       float64
shipping_fee       float64
dtype: object

order_items (37763, 5)
======
unit_price_at_purchase    2262
order_item_id                0
order_id                     0
product_id                   0
quantity                     0
dtype: int64
duplicates: 262
order_item_id               str
order_id                    str
product_id                  str
quantity                  int64
unit_price_at_purchase      str
dtype: object

payments (15000, 6)
======
amount_paid       878
payment_id          0
order_id            0
payment_method      0
payment_status      0
dtype: int64
duplicates: 0
payment_id        str
order_id          str
payment_method    str
payment_status    str
payment_date      str
amount_paid       str
dtype: object

shipments (15000, 7)
======
delivered_date    729
order_id            0
shipment_id         0
courier             0
tracking_no         0
dtype: int64
duplicates: 0
shipment_id        str
order_id           str
courier            str
tracking_no        str
shipment_status    str
ship_date          str
delivered_date     str
dtype: object

returns (1200, 6)
======
refund_amount    187
refunded_flag    110
order_id           0
return_id          0
reason             0
dtype: int64
duplicates: 0
return_id                  str
order_id                   str
return_request_date        str
reason                     str
refunded_flag              str
refund_amount          float64
dtype: object

In [44]:
data['customers']['gender'].value_counts(dropna=False)

gender
M          1310
F          1275
Female      731
Male        725
Unknown     593
NaN         301
female      115
Name: count, dtype: int64

In [27]:
data['products']['category'].value_counts(dropna=False)

category
Beauty              94
Toys                92
Books               90
Fashion             89
Groceries           77
Home & Kitchen      76
Sports              74
Electronics         71
electronics         20
Book                20
Home and Kitchen    19
Electronics         17
Grocery             12
Elec                11
Beauty & Care       11
Toy                 11
Fashon               8
Sports & Outdoor     8
Name: count, dtype: int64

In [28]:
#customers.isna().sum().sort_values(ascending=False)
data['customers'].isna().sum().sort_values(ascending=False)

gender          301
loyalty_tier    266
age             150
phone           147
email           107
first_name        0
last_name         0
customer_id       0
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
dtype: int64

In [35]:
customers_clean = data['customers'].copy()

In [36]:
customers_clean['gender'] = customers_clean['gender'].fillna("Unknown")

In [37]:
customers_clean.isna().sum().sort_values(ascending=False)

loyalty_tier    266
age             150
phone           147
email           107
customer_id       0
gender            0
last_name         0
first_name        0
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
dtype: int64

In [38]:
customers_clean['age'] = customers_clean['age'].fillna(0)

In [39]:
customers_clean['phone'] = customers_clean['phone'].fillna('09100000001')

In [40]:
customers_clean['email'] = customers_clean['email'].fillna('default@gmail.com')

In [41]:
customers_clean['loyalty_tier'] = customers_clean['loyalty_tier'].fillna('Unknown')

In [43]:
returns_clean = data['returns'].copy()

In [46]:
returns_clean['refund_missing'] = returns_clean['refund_amount'].isna()

In [47]:
returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN,True
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False
...,...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74,False
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28,False
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False

In [49]:
shipments_clean = data['shipments']

In [51]:
shipments_clean[shipments_clean["delivered_date"].isna()][
    ["shipment_id", "shipment_status", "ship_date", "delivered_date"]
]

      shipment_id shipment_status    ship_date delivered_date
24     SHP0000025       Delivered   2024-03-19            NaN
27     SHP0000028       Delivered   2024-03-31            NaN
38     SHP0000039       Delivered  13-Oct-2024            NaN
64     SHP0000065       Delivered   2024-01-19            NaN
71     SHP0000072       Delivered   2025-04-03            NaN
...           ...             ...          ...            ...
14916  SHP0014917       Delivered   2024-03-27            NaN
14958  SHP0014959       Delivered   2026-01-23            NaN
14978  SHP0014979       Delivered   2025-12-16            NaN
14981  SHP0014982      In Transit   2025-06-06            NaN
14994  SHP0014995      In Transit   2025-06-11            NaN

[729 rows x 4 columns]

In [52]:
age_analysis = data['customers'].dropna(subset=["age"]).copy()

In [53]:
data['customers'].shape

(5050, 13)

In [54]:
age_analysis.shape

(4900, 13)

In [55]:
5050 - 4900

150

In [56]:
customers_drop = data['customers'].dropna(subset=["age"])

In [58]:
customers_drop.isna().sum()

customer_id       0
first_name        0
last_name         0
gender          290
age               0
email           106
phone           144
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
loyalty_tier    256
dtype: int64

In [3]:
data['customers'].duplicated().sum()

np.int64(50)

In [4]:
data['orders'].duplicated().sum()

np.int64(75)

In [5]:
duplicated_orders = data['orders'][
    data['orders'].duplicated(subset=["order_id"], keep=False)
    ].sort_values("order_id")

In [7]:
duplicated_orders.head(10)

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
15034,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
1082,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15014,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15038,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
1553,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
15027,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
1618,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
15035,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN
1800,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN

In [9]:
orders_clean = data['orders'].copy()

In [12]:
orders_clean.duplicated().sum()

np.int64(0)

In [11]:
orders_clean = data['orders'].drop_duplicates().copy()

In [16]:
orders_clean[orders_clean['order_id'] == "ORD0000649"]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68

In [19]:
orders_clean['order_id'].is_unique

True

In [20]:
data['products']

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [21]:
def clean_currency(series):
    return pd.to_numeric(
        series.astype("string")
              .str.replace(
                  "₱", "", regex=False)
              .str.replace(
                  ",", "", regex=False)
              .str.strip(),
        errors="coerce"
    )

In [30]:
products_clean['unit_price_num'] = clean_currency(
    products_clean['unit_price']
)

In [26]:
data['products'] = data['products'].drop(columns='unit_price_num')

In [29]:
products_clean = data['products'].copy()

In [33]:
products_clean['unit_price_num']

0        64.5
1       70.39
2       70.26
3       62.46
4       82.02
        ...
795    132.12
796     62.54
797    112.46
798     34.96
799    116.39
Name: unit_price_num, Length: 800, dtype: Float64

In [46]:
customers_clean['gender']

0       Unknown
1        Female
2          Male
3             F
4          Male
         ...
5045          F
5046          F
5047    Unknown
5048          M
5049          M
Name: gender, Length: 5050, dtype: str

In [45]:
# M          1310
# F          1275
# Female      731
# Male        725
# Unknown     593
# NaN         301
# female      115
customers_clean["gender_clean"] = (
    customers_clean["gender"]
      .astype("string")
      .str.strip()
      .str.lower()
      .replace({
          "m": "Male",
          "male": "Male",
          "M": "Male",
          "f": "Female",
          "F": "Female",
          "female": "Female",
          "unknown": "Unknown"
      })
      .fillna("Unknown")
)

In [47]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male

In [49]:
data['products']['category'].value_counts()

category
Beauty              94
Toys                92
Books               90
Fashion             89
Groceries           77
Home & Kitchen      76
Sports              74
Electronics         71
electronics         20
Book                20
Home and Kitchen    19
Electronics         17
Grocery             12
Elec                11
Beauty & Care       11
Toy                 11
Fashon               8
Sports & Outdoor     8
Name: count, dtype: int64

In [136]:
products_clean = data['products'].copy()

In [137]:
category_base = (
    products_clean["category"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [138]:
category_map = {
    "electronics": "Electronics",
    "elec": "Electronics",
    "book": "Books",
    "books": "Books",
    "grocery": "Groceries",
    "groceries": "Groceries",
    "home and kitchen": "Home & Kitchen",
    "home & kitchen": "Home & Kitchen",
    "toy": "Toys",
    "toys": "Toys",
    "beauty & care": "Beauty",
    "beauty": "Beauty",
    "fashon": "Fashion",
    "fashion": "Fashion",
    "sports & outdoor": "Sports",
    "sports": "Sports"
}

In [139]:
products_clean['category_clean'] = category_base.replace(category_map)

In [132]:
products_clean['category'].value_counts()

category
Electronics       119
Books             110
Beauty            105
Toys              103
Fashion            97
Home & Kitchen     95
Groceries          89
Sports             82
Name: count, dtype: Int64

In [60]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73
...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03

In [61]:
orders_clean["order_datetime_clean"] = pd.to_datetime(
    orders_clean["order_datetime"],
    format="mixed",
    errors="coerce"
)

In [62]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00
...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00

In [63]:
orders_clean['order_datetime'].dtype

In [65]:
orders_clean.dtypes

order_id                           str
customer_id                        str
order_datetime                     str
order_status                       str
sales_channel                      str
shipping_method                    str
discount_pct                   float64
shipping_fee                   float64
order_datetime_clean    datetime64[us]
dtype: object

In [66]:
shipments_clean = data["shipments"]

In [67]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025

In [68]:
shipments_clean["ship_date_clean"] = pd.to_datetime(
    shipments_clean["ship_date"],
    format="mixed",
    errors="coerce"
)

In [69]:
shipments_clean["delivered_date_clean"] = pd.to_datetime(
    shipments_clean["delivered_date"],
    format="mixed",
    errors="coerce"
)

In [70]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date,ship_date_clean,delivered_date_clean
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025,2025-09-05,2025-09-06
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025,2025-07-18,2025-07-19

In [71]:
#calculate delivery duration
shipments_clean["delivery_days"] = (
    shipments_clean["delivered_date_clean"] - shipments_clean["ship_date_clean"]
).dt.days

In [72]:
shipments_clean["delivery_days"].describe()

count    14271.000000
mean         3.997968
std          1.991026
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          7.000000
Name: delivery_days, dtype: float64

In [73]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date,ship_date_clean,delivered_date_clean,delivery_days
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025,2025-09-05,2025-09-06,1.0
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12,2025-02-06,2025-02-12,6.0
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29,2025-07-23,2025-07-29,6.0
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25,2025-01-21,2025-01-25,4.0
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26,2025-09-21,2025-09-26,5.0
...,...,...,...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23,2024-02-21,2024-02-23,2.0
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03,2024-01-27,2024-02-03,7.0
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29,2025-01-25,2025-01-29,4.0
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26,2024-05-22,2024-05-26,4.0
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025,2025-07-18,2025-07-19,1.0

In [74]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00
...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00

In [77]:
# 'Y' or 'A': Year
# 'Q': Quarter
# 'M': Month
# 'W': Week
# 'D': Day
orders_clean["order_month"] = (
    orders_clean["order_datetime_clean"].dt.to_period("M")
)

In [76]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,2025-11
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,2025-09
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,2025-08
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,2025-10
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,2024-05
...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,2025-02
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,2024-10
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,2026-01
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,2024-08
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,2025-07

In [78]:
negative_age = customers_clean['age'] < 0

In [80]:
negative_age.sum()

np.int64(49)

In [81]:
customers_clean.loc[negative_age, ["customer_id", "age"]].head()

    customer_id  age
162  CUST000163 -1.0
329  CUST000330 -1.0
696  CUST000697 -1.0
718  CUST000719 -1.0
872  CUST000873 -1.0

In [82]:
under_18 = customers_clean["age"].between(0,17)

In [83]:
under_18.sum()

np.int64(569)

In [84]:
zero_qty = customers_clean["age"] <= 0

In [85]:
zero_qty.sum()

np.int64(200)

In [86]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male

In [97]:
invalid_age = negative_age | under_18 | zero_qty

In [98]:
invalid_age.sum()

np.int64(618)

In [99]:
customers_clean.loc[invalid_age, "age_clean"] = np.nan

In [101]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean,age_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown,20.0
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female,35.0
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male,NaN
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female,26.0
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female,33.0
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female,41.0
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown,25.0
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male,NaN
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male,28.0

In [102]:
missing_customers = (
    set(orders_clean["customer_id"]) - set(customers_clean["customer_id"])
)

In [106]:
missing_customers

{'CUST999999'}

In [107]:
orphan_order_rows = orders_clean[
    ~orders_clean["customer_id"].isin(customers_clean["customer_id"])
    # ~ = NOT
]

In [112]:
orphan_order_rows

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
602,ORD0000603,CUST999999,01/02/2024 09:07 PM,Shipped,Web,Express,0.101,100.45,2024-01-02 21:07:00,2024-01
756,ORD0000757,CUST999999,2025-05-19 14:53:00,Completed,Web,Standard,0.005,71.00,2025-05-19 14:53:00,2025-05
806,ORD0000807,CUST999999,2024-04-06 03:40:00,Completed,Web,Standard,0.194,94.34,2024-04-06 03:40:00,2024-04
1478,ORD0001479,CUST999999,2024-04-02 23:15:00,Completed,Mobile App,Express,0.161,107.78,2024-04-02 23:15:00,2024-04
1855,ORD0001856,CUST999999,2024-08-08 01:40:00,Completed,Mobile App,Express,0.080,101.14,2024-08-08 01:40:00,2024-08
2770,ORD0002771,CUST999999,2025-01-28 12:40:00,Completed,Mobile App,Pickup,0.091,100.96,2025-01-28 12:40:00,2025-01
2919,ORD0002920,CUST999999,2024-10-21 09:50:00,Completed,Marketplace,Pickup,0.067,74.64,2024-10-21 09:50:00,2024-10
3569,ORD0003570,CUST999999,06/05/2024 09:24 AM,Cancelled,Web,Express,0.029,104.07,2024-06-05 09:24:00,2024-06
3760,ORD0003761,CUST999999,2025-11-20 20:33:00,Returned,Marketplace,Pickup,0.000,94.26,2025-11-20 20:33:00,2025-11
4881,ORD0004882,CUST999999,2025-05-16 16:56:00,Completed,Mobile App,Express,0.000,64.93,2025-05-16 16:56:00,2025-05
4887,ORD0004888,CUST999999,10/15/2025 07:31 AM,Completed,Web,Pickup,0.000,122.26,2025-10-15 07:31:00,2025-10
4891,ORD0004892,CUST999999,2024-05-07 17:14:00,Pending,Mobile App,Express,0.114,62.66,2024-05-07 17:14:00,2024-05
5064,ORD0005065,CUST999999,2026-01-17 05:27:00,Completed,Marketplace,Pickup,0.000,85.11,2026-01-17 05:27:00,2026-01
5128,ORD0005129,CUST999999,03/29/2024 12:39 PM,Completed,Mobile App,Standard,NaN,37.05,2024-03-29 12:39:00,2024-03
5292,ORD0005293,CUST999999,2025-10-16 20:56:00,Completed,Marketplace,Pickup,0.302,49.99,2025-10-16 20:56:00,2025-10
5402,ORD0005403,CUST999999,2024-06-25 12:32:00,Completed,Mobile App,Standard,0.000,151.33,2024-06-25 12:32:00,2024-06
5674,ORD0005675,CUST999999,09/09/2025 10:48 PM,Completed,Marketplace,Pickup,NaN,70.47,2025-09-09 22:48:00,2025-09
5898,ORD0005899,CUST999999,2026-01-01 10:01:00,Cancelled,Marketplace,Express,0.140,5.59,2026-01-01 10:01:00,2026-01
6121,ORD0006122,CUST999999,03/03/2024 10:54 PM,Pending,Marketplace,Standard,0.080,111.26,2024-03-03 22:54:00,2024-03
6125,ORD0006126,CUST999999,2024-08-05 03:11:00,Completed,Mobile App,Standard,0.000,92.05,2024-08-05 03:11:00,2024-08
6272,ORD0006273,CUST999999,2025-06-03 19:59:00,Completed,Web,Standard,0.046,57.76,2025-06-03 19:59:00,2025-06
6833,ORD0006834,CUST999999,2024-05-17 20:59:00,Completed,Marketplace,Pickup,0.075,61.71,2024-05-17 20:59:00,2024-05
6886,ORD0006887,CUST999999,2025-02-23 19:26:00,Completed,Mobile App,Standard,0.039,59.69,2025-02-23 19:26:00,2025-02
7295,ORD0007296,CUST999999,2024-05-31 16:42:00,Pending,Web,Standard,0.156,37.85,2024-05-31 16:42:00,2024-05
7720,ORD0007721,CUST999999,06/05/2025 07:16 AM,Completed,Web,Pickup,0.089,95.38,2025-06-05 07:16:00,2025-06
7721,ORD0007722,CUST999999,2024-03-06 14:18:00,Completed,Web,Standard,0.071,134.71,2024-03-06 14:18:00,2024-03
8155,ORD0008156,CUST999999,2025-08-18 08:45:00,Completed,Web,Pickup,0.180,11.76,2025-08-18 08:45:00,2025-08
8237,ORD0008238,CUST999999,07/12/2024 09:03 PM,Completed,Mobile App,Standard,0.014,61.38,2024-07-12 21:03:00,2024-07
8313,ORD0008314,CUST999999,2024-07-21 18:26:00,Completed,Marketplace,Express,0.105,88.69,2024-07-21 18:26:00,2024-07
8580,ORD0008581,CUST999999,11/12/2025 12:34 AM,Completed,Mobile App,Standard,0.000,87.17,2025-11-12 00:34:00,2025-11
9338,ORD0009339,CUST999999,03/12/2024 02:23 PM,Cancelled,Mobile App,Pickup,0.076,70.38,2024-03-12 14:23:00,2024-03
9533,ORD0009534,CUST999999,16-Apr-2024 22:51,Completed,Marketplace,Pickup,0.000,99.03,2024-04-16 22:51:00,2024-04
10284,ORD0010285,CUST999999,27-Feb-2025 02:46,Cancelled,Web,Standard,0.074,165.93,2025-02-27 02:46:00,2025-02
10365,ORD0010366,CUST999999,2024-05-05 02:10:00,Completed,Mobile App,Pickup,0.229,93.97,2024-05-05 02:10:00,2024-05
10457,ORD0010458,CUST999999,2024-06-29 10:36:00,Completed,Marketplace,Standard,0.000,112.26,2024-06-29 10:36:00,2024-06
10675,ORD0010676,CUST999999,2025-02-28 12:31:00,Pending,Web,Express,0.076,89.33,2025-02-28 12:31:00,2025-02
10791,ORD0010792,CUST999999,2024-04-11 16:04:00,Completed,Marketplace,Express,0.169,59.91,2024-04-11 16:04:00,2024-04
11224,ORD0011225,CUST999999,04/24/2024 04:52 PM,Completed,Mobile App,Express,NaN,120.16,2024-04-24 16:52:00,2024-04
12257,ORD0012258,CUST999999,2024-07-09 18:38:00,Completed,Mobile App,Express,0.066,116.58,2024-07-09 18:38:00,2024-07
12901,ORD0012902,CUST999999,2024-01-27 17:20:00,Completed,Web,Express,0.054,106.20,2024-01-27 17:20:00,2024-01
13188,ORD0013189,CUST999999,26-Jan-2026 08:37,Returned,Marketplace,Express,0.162,88.99,2026-01-26 08:37:00,2026-01
14196,ORD0014197,CUST999999,09-Jan-2024 16:47,Completed,Mobile App,Express,0.127,40.38,2024-01-09 16:47:00,2024-01
14450,ORD0014451,CUST999999,01/05/2025 08:55 AM,Completed,Marketplace,Express,0.003,2.08,2025-01-05 08:55:00,2025-01

In [114]:
products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home & Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Electronics,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [115]:
items_clean = data['order_items'].drop_duplicates().copy()

In [116]:
missing_products = (
    set(items_clean["product_id"]) - set(data['products']["product_id"])
)

In [117]:
missing_products

{'PROD00000'}

In [118]:
orphan_product_rows = items_clean[
    ~items_clean["product_id"].isin(data["products"]["product_id"])
]

In [119]:
orphan_product_rows

       order_item_id    order_id product_id  quantity unit_price_at_purchase
377    ITEM000000378  ORD0000148  PROD00000         1                  106.4
601    ITEM000000602  ORD0000241  PROD00000         1                  54.41
692    ITEM000000693  ORD0000275  PROD00000         2                 135.29
935    ITEM000000936  ORD0000370  PROD00000         1                  30.34
1108   ITEM000001109  ORD0000435  PROD00000         1                  95.17
...              ...         ...        ...       ...                    ...
37231  ITEM000037232  ORD0014893  PROD00000         3                 161.46
37339  ITEM000037340  ORD0014935  PROD00000         6                  188.5
37373  ITEM000037374  ORD0014952  PROD00000         1                 137.74
37464  ITEM000037465  ORD0014986  PROD00000         4                  58.28
37496  ITEM000037497  ORD0014999  PROD00000         1                  63.45

[129 rows x 5 columns]

In [120]:
audit = items_clean.merge(
    data["products"][["product_id", "product_name"]],
    on="product_id",
    how="left",
    indicator=True
)

In [123]:
audit

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,product_name,_merge
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,HomeEase Sports 313,both
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,NovaTech Beauty 892,both
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,BookNest Electronics 252,both
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,GlowCo Groceries 689,both
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,BookNest Home 591,both
...,...,...,...,...,...,...,...
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,NaN,left_only
37497,ITEM000037498,ORD0014999,PROD00138,1,128.96,KidJoy Toys 976,both
37498,ITEM000037499,ORD0014999,PROD00689,3,NaN,FreshCart Sports 375,both
37499,ITEM000037500,ORD0015000,PROD00376,2,208.44,KidJoy Beauty 728,both
37500,ITEM000037501,ORD0015000,PROD00584,2,63.2,HomeEase Electronics 592,both

In [140]:
items_analysis = items_clean.copy()

items_analysis["purchase_price_num"] = (
    clean_currency(
        items_analysis["unit_price_at_purchase"]
    )
)

items_analysis = items_analysis[
    (items_analysis["quantity"] > 0)
    & items_analysis["purchase_price_num"].notna()
]

items_analysis = items_analysis.merge(
    products_clean[["product_id", "unit_cost",
              "category_clean"]],
    on="product_id", how="left"
)

items_analysis["line_revenue"] = (
    items_analysis["quantity"]
    * items_analysis["purchase_price_num"]
)

items_analysis["line_cost"] = (
    items_analysis["quantity"]
    * items_analysis["unit_cost"]
)

In [143]:
items_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,71.15,Sports,241.34,142.30
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,63.11,Beauty,167.16,126.22
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,30.08,Electronics,93.92,60.16
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,55.82,Groceries,100.59,55.82
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,74.36,Home & Kitchen,109.18,74.36
...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,56.45,Home & Kitchen,69.64,56.45
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,NaN,<NA>,63.45,NaN
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,96.76,Toys,128.96,96.76
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,124.37,Beauty,416.88,248.74
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,40.73,Electronics,126.4,81.46

In [151]:
sales_analysis = items_analysis.merge(
    orders_clean[[
        "order_id", "sales_channel", "order_status"
    ]],
    on="order_id", how="left"
)

channel_summary = (
    sales_analysis
    .groupby("sales_channel")
    .agg(
        gross_line_revenue=("line_revenue", "sum"),
        average_line_revenue=("line_revenue", "mean"),
        line_items=("order_item_id", "count"),
        orders=("order_id", "nunique")
    )
    .sort_values(
        "gross_line_revenue", ascending=False
    )
)

print(channel_summary)

               gross_line_revenue  average_line_revenue  line_items  orders
sales_channel
Web                    2324877.34            199.972247       11626    4885
Marketplace            2312808.93            198.337101       11661    4961
Mobile App             2290206.85            197.007041       11625    4912

In [145]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,2025-11
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,2025-09
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,2025-08
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,2025-10
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,2024-05
...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,2025-02
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,2024-10
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,2026-01
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,2024-08
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,2025-07

In [152]:
sales_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost,line_profit,sales_channel,order_status
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,71.15,Sports,241.34,142.30,99.04,Marketplace,Cancelled
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,63.11,Beauty,167.16,126.22,40.94,Marketplace,Completed
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,30.08,Electronics,93.92,60.16,33.76,Marketplace,Completed
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,55.82,Groceries,100.59,55.82,44.77,Marketplace,Completed
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,74.36,Home & Kitchen,109.18,74.36,34.82,Marketplace,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,56.45,Home & Kitchen,69.64,56.45,13.19,Web,Shipped
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,NaN,<NA>,63.45,NaN,<NA>,Web,Shipped
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,96.76,Toys,128.96,96.76,32.2,Web,Shipped
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,124.37,Beauty,416.88,248.74,168.14,Marketplace,Completed
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,40.73,Electronics,126.4,81.46,44.94,Marketplace,Completed

In [153]:
numeric_cols = [
    "quantity",
    "purchase_price_num",
    "line_revenue",
    "unit_cost",
    "line_profit"
]

corr = sales_analysis[numeric_cols].corr()

In [149]:
items_analysis["line_profit"] = (
    items_analysis["line_revenue"] - items_analysis["line_cost"]
)

In [154]:
corr

,quantity,purchase_price_num,line_revenue,unit_cost,line_profit
quantity,1.000000,0.001140,0.698421,0.002091,0.598136
purchase_price_num,0.001140,1.000000,0.617143,0.953349,0.630298
line_revenue,0.698421,0.617143,1.000000,0.591242,0.939665
unit_cost,0.002091,0.953349,0.591242,1.000000,0.517592
line_profit,0.598136,0.630298,0.939665,0.517592,1.000000

In [159]:
q1 = sales_analysis["line_revenue"].quantile(0.25)
q3 = sales_analysis["line_revenue"].quantile(0.75)
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = sales_analysis[
    (sales_analysis["line_revenue"] < lower)
    | (sales_analysis["line_revenue"] > upper)
]

print(outliers[[
    "order_id", "product_id", "quantity",
    "purchase_price_num", "line_revenue"
]].tail())

         order_id product_id  quantity  purchase_price_num  line_revenue
34826  ORD0014963  PROD00414         4              178.96        715.84
34830  ORD0014965  PROD00599         6              134.99        809.94
34835  ORD0014968  PROD00452         3              186.71        560.13
34873  ORD0014984  PROD00090         5              109.18         545.9
34898  ORD0014995  PROD00443         3              188.24        564.72

In [156]:
outliers

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost,line_profit,sales_channel,order_status
34,ITEM000000038,ORD0000012,PROD00261,5,144.3,144.3,94.04,Beauty,721.5,470.20,251.3,Web,Shipped
92,ITEM000000103,ORD0000036,PROD00108,5,127.69,127.69,80.81,Electronics,638.45,404.05,234.4,Mobile App,Completed
101,ITEM000000113,ORD0000041,PROD00695,4,217.27,217.27,117.38,Fashion,869.08,469.52,399.56,Web,Completed
108,ITEM000000120,ORD0000043,PROD00562,6,86.08,86.08,71.63,Books,516.48,429.78,86.7,Marketplace,Completed
110,ITEM000000123,ORD0000045,PROD00356,6,123.8,123.8,80.45,Electronics,742.8,482.70,260.1,Marketplace,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34826,ITEM000037407,ORD0014963,PROD00414,4,178.96,178.96,101.43,Sports,715.84,405.72,310.12,Marketplace,Returned
34830,ITEM000037412,ORD0014965,PROD00599,6,134.99,134.99,90.98,Home & Kitchen,809.94,545.88,264.06,Web,Shipped
34835,ITEM000037418,ORD0014968,PROD00452,3,186.71,186.71,110.01,Groceries,560.13,330.03,230.1,Web,Completed
34873,ITEM000037461,ORD0014984,PROD00090,5,109.18,109.18,74.36,Home & Kitchen,545.9,371.80,174.1,Mobile App,Completed
34898,ITEM000037486,ORD0014995,PROD00443,3,188.24,188.24,123.39,Groceries,564.72,370.17,194.55,Marketplace,Returned

In [158]:
sales_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost,line_profit,sales_channel,order_status
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,71.15,Sports,241.34,142.30,99.04,Marketplace,Cancelled
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,63.11,Beauty,167.16,126.22,40.94,Marketplace,Completed
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,30.08,Electronics,93.92,60.16,33.76,Marketplace,Completed
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,55.82,Groceries,100.59,55.82,44.77,Marketplace,Completed
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,74.36,Home & Kitchen,109.18,74.36,34.82,Marketplace,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,56.45,Home & Kitchen,69.64,56.45,13.19,Web,Shipped
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,NaN,<NA>,63.45,NaN,<NA>,Web,Shipped
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,96.76,Toys,128.96,96.76,32.2,Web,Shipped
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,124.37,Beauty,416.88,248.74,168.14,Marketplace,Completed
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,40.73,Electronics,126.4,81.46,44.94,Marketplace,Completed

In [ ]:
Q1 = 100
Q2 = 200
IQR = 200 - 100 => 100

LB = 100 - (1.5 * 100) => -50
UB = 200 + (1.5 * 100) => 350